//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace Oduna.Lib.Group {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GroupSoap", Namespace="http://tempuri.org/")]
    public partial class Group : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ClearAllCacheOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClearGroupCacheOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClearDepartmentCacheOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Group() {
            this.Url = global::Oduna.Lib.Properties.Settings.Default.Oduna_Lib_Group_Group;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ClearAllCacheCompletedEventHandler ClearAllCacheCompleted;
        
        /// <remarks/>
        public event ClearGroupCacheCompletedEventHandler ClearGroupCacheCompleted;
        
        /// <remarks/>
        public event ClearDepartmentCacheCompletedEventHandler ClearDepartmentCacheCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ClearAllCache", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ClearAllCache() {
            this.Invoke("ClearAllCache", new object[0]);
        }
        
        /// <remarks/>
        public void ClearAllCacheAsync() {
            this.ClearAllCacheAsync(null);
        }
        
        /// <remarks/>
        public void ClearAllCacheAsync(object userState) {
            if ((this.ClearAllCacheOperationCompleted == null)) {
                this.ClearAllCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearAllCacheOperationCompleted);
            }
            this.InvokeAsync("ClearAllCache", new object[0], this.ClearAllCacheOperationCompleted, userState);
        }
        
        private void OnClearAllCacheOperationCompleted(object arg) {
            if ((this.ClearAllCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearAllCacheCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ClearGroupCache", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ClearGroupCache() {
            this.Invoke("ClearGroupCache", new object[0]);
        }
        
        /// <remarks/>
        public void ClearGroupCacheAsync() {
            this.ClearGroupCacheAsync(null);
        }
        
        /// <remarks/>
        public void ClearGroupCacheAsync(object userState) {
            if ((this.ClearGroupCacheOperationCompleted == null)) {
                this.ClearGroupCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearGroupCacheOperationCompleted);
            }
            this.InvokeAsync("ClearGroupCache", new object[0], this.ClearGroupCacheOperationCompleted, userState);
        }
        
        private void OnClearGroupCacheOperationCompleted(object arg) {
            if ((this.ClearGroupCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearGroupCacheCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ClearDepartmentCache", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ClearDepartmentCache() {
            this.Invoke("ClearDepartmentCache", new object[0]);
        }
        
        /// <remarks/>
        public void ClearDepartmentCacheAsync() {
            this.ClearDepartmentCacheAsync(null);
        }
        
        /// <remarks/>
        public void ClearDepartmentCacheAsync(object userState) {
            if ((this.ClearDepartmentCacheOperationCompleted == null)) {
                this.ClearDepartmentCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearDepartmentCacheOperationCompleted);
            }
            this.InvokeAsync("ClearDepartmentCache", new object[0], this.ClearDepartmentCacheOperationCompleted, userState);
        }
        
        private void OnClearDepartmentCacheOperationCompleted(object arg) {
            if ((this.ClearDepartmentCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearDepartmentCacheCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ClearAllCacheCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ClearGroupCacheCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ClearDepartmentCacheCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591